version: '3.7'

x-default-logging: &default
  {}

x-loki-logging: &loki
  driver: loki
  options:
    loki-url: http://localhost:3100/loki/api/v1/push
    mode: non-blocking
    max-buffer-size: 4m
    loki-retries: "3"

x-log-config: &log-config
  # update this value to *loki if needed to see logs in grafana dashboard.
  <<: *loki

services:

  proxy:
    image: '485402728093.dkr.ecr.ap-south-1.amazonaws.com/bahmni-msf-lite/proxy:${PROXY_IMAGE_TAG:?}'
    #volumes:
      # - ${CERTIFICATE_PATH}:/etc/tls
    ports:
      - '80:80'
      - '443:443'
    logging: *log-config
    environment:
      TZ: ${TZ}

  bahmni-config:
    image: '485402728093.dkr.ecr.ap-south-1.amazonaws.com/bahmni-msf-lite/amman-config:${CONFIG_IMAGE_TAG:?}'
    volumes:
      - '${CONFIG_VOLUME:?}:/usr/local/bahmni_config'
    logging: *log-config

  openmrs:
    profiles: ["emr","bahmni-lite","bahmni-mart"]
    image: 485402728093.dkr.ecr.ap-south-1.amazonaws.com/bahmni-msf-lite/openmrs-amman:${OPENMRS_IMAGE_TAG:?}
    environment:
      TZ: ${TZ}
      OMRS_DB_NAME: ${OPENMRS_DB_NAME:?}
      OMRS_DB_HOSTNAME: ${OPENMRS_DB_HOST:?}
      OMRS_DB_USERNAME: ${OPENMRS_DB_USERNAME:?}
      OMRS_DB_PASSWORD: ${OPENMRS_DB_PASSWORD:?}
      OMRS_CREATE_TABLES: ${OPENMRS_DB_CREATE_TABLES}
      OMRS_AUTO_UPDATE_DATABASE: ${OPENMRS_DB_AUTO_UPDATE}
      OMRS_MODULE_WEB_ADMIN: ${OPENMRS_MODULE_WEB_ADMIN}
      # OMRS_DEV_DEBUG_PORT: ${OMRS_DEV_DEBUG_PORT}
      OMRS_JAVA_SERVER_OPTS: ${OMRS_JAVA_SERVER_OPTS}
      OMRS_JAVA_MEMORY_OPTS: ${OMRS_JAVA_MEMORY_OPTS}
      SEND_MAIL: ${SEND_MAIL}
      MAIL_TRANSPORT_PROTOCOL: ${MAIL_TRANSPORT_PROTOCOL}
      MAIL_SMTP_HOST: ${MAIL_SMTP_HOST}
      MAIL_SMTP_PORT: ${MAIL_SMTP_PORT}
      MAIL_SMTP_AUTH: ${MAIL_SMTP_AUTH}
      MAIL_SMTP_STARTTLS_ENABLE: ${MAIL_SMTP_STARTTLS_ENABLE}
      MAIL_SMTP_SSL_ENABLE: ${MAIL_SMTP_SSL_ENABLE}
      MAIL_DEBUG: ${MAIL_DEBUG}
      MAIL_FROM: ${MAIL_FROM}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      OMRS_DOCKER_ENV: ${OPENMRS_DOCKER_ENV}
      OMRS_C3P0_MAX_SIZE: ${OMRS_C3P0_MAX_SIZE}
    #ports:
      # - ${OMRS_DEV_DEBUG_PORT}:${OMRS_DEV_DEBUG_PORT}
    volumes:
      - "${CONFIG_VOLUME:?}:/etc/bahmni_config/:ro"
      - "bahmni-lab-results:/home/bahmni/uploaded_results"
      - "bahmni-uploaded-files:/home/bahmni/uploaded-files"
      # - "${BAHMNI_OPENMRS_MODULES_PATH:?}/:/openmrs/data/modules/"
      - 'bahmni-patient-images:/home/bahmni/patient_images'
      - 'bahmni-document-images:/home/bahmni/document_images'
      - 'bahmni-clinical-forms:/home/bahmni/clinical_forms'
      - 'configuration_checksums:/openmrs/data/configuration_checksums'
      - "amman-exports:/home/bahmni/amman_export/:ro"

    depends_on:
      - openmrsdb
    logging: *log-config

  openmrsdb:
    image: 485402728093.dkr.ecr.ap-south-1.amazonaws.com/bahmni-lite/mysql:${OPENMRS_DB_IMAGE_NAME:?}
    restart: always
    profiles: ["emr","bahmni-lite", "metabase", "bahmni-mart"]
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      TZ: ${TZ}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?}
      MYSQL_DATABASE: ${OPENMRS_DB_NAME:?}
      MYSQL_USER: ${OPENMRS_DB_USERNAME:?}
      MYSQL_PASSWORD: ${OPENMRS_DB_PASSWORD:?}
    volumes:
      - "./openmrsdb/docker.cnf:/etc/mysql/conf.d/docker.cnf"
      - 'openmrsdbdata:/var/lib/mysql'
      - 'configuration_checksums:/configuration_checksums'

    logging: *log-config

  metabasedb:
    image: 485402728093.dkr.ecr.ap-south-1.amazonaws.com/bahmni-lite/postgres:${METABASE_POSTGRES_IMAGE_TAG:?}
    restart: on-failure:[3]
    profiles: ["metabase", "bahmni-mart", "emr"]
    environment:
      TZ: ${TZ}
      POSTGRES_DB: ${METABASE_DB_NAME:?}
      POSTGRES_USER: ${METABASE_DB_USER:?}
      POSTGRES_PASSWORD: ${METABASE_DB_PASSWORD:?}
    volumes:
      - 'metabase-data:/var/lib/postgresql/data'

  metabase:
    image: 485402728093.dkr.ecr.ap-south-1.amazonaws.com/bahmni-lite/bahmni/bahmni-metabase:${METABASE_IMAGE_TAG:?}
    restart: on-failure:[3]
    ports:
      - "9003:3000"
    profiles: ["metabase", "bahmni-mart", "emr"]
    environment:
      TZ: ${TZ}
      MB_ADMIN_EMAIL: ${METABASE_ADMIN_EMAIL:?}
      MB_ADMIN_FIRST_NAME: ${METABASE_ADMIN_FIRST_NAME:?}
      MB_ADMIN_PASSWORD: ${METABASE_ADMIN_PASSWORD:?}
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: ${METABASE_DB_NAME:?}
      MB_DB_PORT:  ${METABASE_DB_PORT:?}
      MB_DB_USER: ${METABASE_DB_USER:?}
      MB_DB_PASS: ${METABASE_DB_PASSWORD:?}
      MB_DB_HOST: ${METABASE_DB_HOST:?}
      OPENMRS_DB_HOST: ${OPENMRS_DB_HOST:?}
      OPENMRS_DB_NAME: ${OPENMRS_DB_NAME:?}
      OPENMRS_DB_USERNAME: ${OPENMRS_DB_USERNAME:?}
      OPENMRS_DB_PASSWORD: ${OPENMRS_DB_PASSWORD:?}
      MART_DB_HOST: ${MART_DB_HOST:?}
      MART_DB_NAME: ${MART_DB_NAME:?}
      MART_DB_USERNAME: ${MART_DB_USERNAME:?}
      MART_DB_PASSWORD: ${MART_DB_PASSWORD:?}
    depends_on:
     - metabasedb

  martdb:
    image: 485402728093.dkr.ecr.ap-south-1.amazonaws.com/bahmni-lite/postgres:${BAHMNI_MART_DB_IMAGE_TAG:?}
    profiles: ["bahmni-mart", "emr"]
    environment:
      TZ: ${TZ}
      POSTGRES_DB: ${MART_DB_NAME:?}
      POSTGRES_USER: ${MART_DB_USERNAME:?}
      POSTGRES_PASSWORD: ${MART_DB_PASSWORD:?}
    volumes:
      - 'mart-data:/var/lib/postgresql/data'

  mart:
    image: 485402728093.dkr.ecr.ap-south-1.amazonaws.com/bahmni-msf-lite/mart:${BAHMNI_MART_IMAGE_TAG:?}
    profiles: ["bahmni-mart", "emr"]
    environment:
      TZ: ${TZ}
      CRON_TIME: ${MART_CRON_TIME:?}
      MART_DB_HOST: ${MART_DB_HOST:?}
      MART_DB_NAME: ${MART_DB_NAME:?}
      MART_DB_USERNAME: ${MART_DB_USERNAME:?}
      MART_DB_PASSWORD: ${MART_DB_PASSWORD:?}
      OPENMRS_DB_HOST: ${OPENMRS_DB_HOST:?}
      OPENMRS_DB_NAME: ${OPENMRS_DB_NAME:?}
      OPENMRS_DB_USERNAME: ${OPENMRS_DB_USERNAME:?}
      OPENMRS_DB_PASSWORD: ${OPENMRS_DB_PASSWORD:?}
      DEFAULT_CONFIG_FILE_PATH_FOR_MART: ${DEFAULT_CONFIG_FILE_PATH_FOR_MART}
      BAHMNI_MART_JSON_CONFIG_FILE: ${BAHMNI_MART_JSON_CONFIG_FILE:-/bahmni-mart/conf/bahmni-mart.json}
    depends_on:
     - martdb
     - openmrsdb
     - openmrs
     - reportsdb
     - reports
    volumes:
     - 'bahmni-clinical-forms:/home/bahmni/clinical_forms'
     - '${CONFIG_VOLUME:?}:/home/bahmni/bahmni_config'
     - 'custom-sql:/home/bahmni/custom-sql'

  bahmni-web:
    image: 485402728093.dkr.ecr.ap-south-1.amazonaws.com/bahmni-msf-lite/bahmni-web:${BAHMNI_WEB_IMAGE_TAG:?}
    profiles: ["emr","bahmni-lite","bahmni-mart"]
    volumes:
      - "${CONFIG_VOLUME:?}:/usr/local/apache2/htdocs/bahmni_config/:ro"
    #   - "${BAHMNI_APPS_PATH:?}/ui/app/:/usr/local/apache2/htdocs/bahmni"
    #   - "${BAHMNI_APPS_PATH:?}/ui/node_modules/@bower_components/:/usr/local/apache2/htdocs/bahmni/components"
    logging: *log-config

  implementer-interface:
    image: 485402728093.dkr.ecr.ap-south-1.amazonaws.com/bahmni-msf-lite/implementer-interface:${IMPLEMENTER_INTERFACE_IMAGE_TAG:?}
    profiles: ["implementer-interface","emr","bahmni-lite"]
    #volumes:
    #  - "${IMPLEMENTER_INTERFACE_CODE_PATH:?}/dist:/usr/local/apache2/htdocs/implementer-interface"
    depends_on:
      - openmrs
    logging: *log-config

  print-forms:
    image: 485402728093.dkr.ecr.ap-south-1.amazonaws.com/bahmni-msf-lite/print-forms:${PRINT_FORMS_IMAGE_TAG:?}
    profiles: ["print-forms","emr","bahmni-lite"]
    #volumes:
    #  - "${IMPLEMENTER_INTERFACE_CODE_PATH:?}/dist:/usr/local/apache2/htdocs/implementer-interface"
    depends_on:
      - openmrs
    logging: *log-config

  reports:
    image: 485402728093.dkr.ecr.ap-south-1.amazonaws.com/bahmni-lite/bahmni/reports:${REPORTS_IMAGE_TAG:?}
    profiles: ["reports","bahmni-lite", "emr","bahmni-mart"]
    environment:
      TZ: ${TZ}
      OPENMRS_DB_HOST: ${OPENMRS_DB_HOST:?}
      OPENMRS_DB_NAME: ${OPENMRS_DB_NAME:?}
      OPENMRS_DB_USERNAME: ${OPENMRS_DB_USERNAME:?}
      OPENMRS_DB_PASSWORD: ${OPENMRS_DB_PASSWORD:?}
      OPENMRS_HOST: ${OPENMRS_HOST:?}
      OPENMRS_PORT: ${OPENMRS_PORT:?}
      REPORTS_DB_SERVER: reportsdb
      REPORTS_DB_NAME: ${REPORTS_DB_NAME:?}
      REPORTS_DB_USERNAME: ${REPORTS_DB_USERNAME:?}
      REPORTS_DB_PASSWORD: ${REPORTS_DB_PASSWORD:?}
    volumes:
      - "${CONFIG_VOLUME:?}:/etc/bahmni_config/:ro"
      # - "bahmni-queued-reports:/home/bahmni/reports"
    entrypoint: ["/bin/sh", "-c", "rm -f /tmp/macroTemplates && ln -s /etc/bahmni_config/openmrs/apps/reports/macroTemplates /tmp/ && exec ./start.sh"]
    depends_on:
      - reportsdb
      - openmrsdb
      - bahmni-web
    logging: *log-config

  amman-exports:
    image: 485402728093.dkr.ecr.ap-south-1.amazonaws.com/bahmni-msf-lite/amman-exports:${AMMAN_EXPORTS_IMAGE_TAG:?}
    profiles: ["amman-exports", "emr", "bahmni-lite"]
    environment:
      TZ: ${AMMAN_TIME_ZONE:?}
      OPENMRS_DB_SERVER: ${OPENMRS_DB_SERVER:?}
      OPENMRS_DB_USERNAME: ${OPENMRS_DB_USERNAME:?}
      OPENMRS_DB_PASSWORD: ${OPENMRS_DB_PASSWORD:?}
      AMMAN_EXPORTS_CRON_TIME: ${AMMAN_EXPORTS_CRON_TIME:?}
    volumes:
      - "${CONFIG_VOLUME:?}:/var/www/bahmni_config/:rw"
      - "amman-exports:/home/bahmni/amman_export/:rw"
    depends_on:
      - openmrsdb
    logging: *log-config

  reportsdb:
    platform: linux/amd64
    image: 485402728093.dkr.ecr.ap-south-1.amazonaws.com/bahmni-lite/mysql:5.7
    profiles: ["reports","bahmni-lite", "emr","bahmni-mart"]
    environment:
      TZ: ${TZ}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?}
      MYSQL_DATABASE: ${REPORTS_DB_NAME:?}
      MYSQL_USER: ${REPORTS_DB_USERNAME:?}
      MYSQL_PASSWORD: ${REPORTS_DB_PASSWORD:?}
    volumes:
      - "./reportsdb/my.cnf:/etc/my.cnf"
      # - 'reportsdbdata:/var/lib/mysql'
    logging: *log-config

  patient-documents:
    image: '485402728093.dkr.ecr.ap-south-1.amazonaws.com/bahmni-lite/bahmni/patient-documents:${PATIENT_DOCUMENTS_TAG:?}'
    profiles: ["emr","bahmni-lite"]
    volumes:
      - 'bahmni-document-images:/usr/share/nginx/html/document_images'
      - 'bahmni-lab-results:/usr/share/nginx/html/uploaded_results'
      - 'bahmni-uploaded-files:/usr/share/nginx/html/uploaded-files'
    environment:
      TZ: ${TZ}
      OPENMRS_HOST: ${OPENMRS_HOST:?}
    depends_on:
      - openmrs
    logging: *log-config

  appointments:
    image: 485402728093.dkr.ecr.ap-south-1.amazonaws.com/bahmni-msf-lite/appointments:${APPOINTMENTS_IMAGE_TAG:?}
    profiles: ["emr","bahmni-lite"]
    # volumes:
    # - "${APPOINTMENTS_PATH:?}/dist/:/usr/local/apache2/htdocs/appointments"

  restore_volumes:
    image: bash:5.2.15
    profiles: ["restore"]
    command: "bash /restore_docker_volumes.sh"
    volumes:
        - "${RESTORE_ARTIFACTS_PATH}:/restore-artifacts"
        - '../backup_restore/restore_docker_volumes.sh:/restore_docker_volumes.sh'
        - 'bahmni-patient-images:/mounts/bahmni-patient-images'
        - 'bahmni-document-images:/mounts/bahmni-document-images'
        - 'bahmni-clinical-forms:/mounts/bahmni-clinical-forms'
        - 'bahmni-lab-results:/mounts/bahmni-lab-results'
        - 'bahmni-uploaded-files:/mounts/bahmni-uploaded-files'
        - 'bahmni-queued-reports:/mounts/bahmni-queued-reports'
        - 'configuration_checksums:/mounts/configuration_checksums'
        - 'custom-sql:/mounts/custom-sql'

volumes:
  openmrs-data:
  openmrsdbdata:
  bahmni-patient-images:
  bahmni-document-images:
  bahmni-clinical-forms:
  bahmni-uploaded-files:
  bahmni-config:
  configuration_checksums:
  mart-data:
  metabase-data:
  bahmni-lab-results:
  amman-exports:
  bahmni-queued-reports:
  custom-sql:
